FROM nginx:1.17.4

EXPOSE 80
EXPOSE 8000

ENV SERVER_NAME default_server

# Copy the template configuration for nginx
# This template is later changed to default.conf when the container is started
COPY default.conf.template /etc/nginx/conf.d/default.conf.template
COPY . /usr/share/nginx/html/

# envsubst takes default.conf.template, replaces environment variables and creates default.conf
# This lets us change the API URL or the server dynamically when we run the image
CMD /bin/bash -c "envsubst '\$SERVER_NAME' < /etc/nginx/conf.d/default.conf.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"